import js from '@eslint/js';
import tseslint from 'typescript-eslint';
import prettier from 'eslint-config-prettier';

export default tseslint.config(
  {
    ignores: [
      '**/node_modules/**',
      '**/.next/**',
      '**/dist/**',
      '**/generated/**',
      'docs/_legacy-ahn-orbit/**',
      'packages/db/prisma/migrations/**',
      'packages/db/generated/**',
      // Generated by Next on every build; not ours to lint.
      'apps/web/next-env.d.ts',
      // Development-only helpers that run outside the app runtime.
      'scripts/**',
    ],
  },
  js.configs.recommended,
  ...tseslint.configs.recommended,
  prettier,
  {
    rules: {
      '@typescript-eslint/no-unused-vars': [
        'error',
        { argsIgnorePattern: '^_', varsIgnorePattern: '^_' },
      ],
      '@typescript-eslint/consistent-type-imports': [
        'error',
        { prefer: 'type-imports', fixStyle: 'inline-type-imports' },
      ],
      'no-restricted-syntax': [
        'error',
        {
          // Inherited from AHN Orbit: time must be injectable so SLA maths is testable.
          selector: 'NewExpression[callee.name="Date"][arguments.length=0]',
          message: 'new Date() is banned - use clock.now() from @relay/core.',
        },
      ],
    },
  },
  {
    // The clock itself; and the seed, whose whole job is manufacturing a
    // plausible history relative to the real wall clock.
    files: ['packages/core/src/clock.ts', 'packages/db/prisma/seed.ts'],
    rules: { 'no-restricted-syntax': 'off' },
  },
  {
    // The web app must never consume queue jobs - it only produces them.
    files: ['apps/web/**/*.{ts,tsx}'],
    rules: {
      'no-restricted-imports': [
        'error',
        {
          paths: [
            {
              name: '@prisma/client',
              message: 'Import from @relay/db - only packages/db may construct a PrismaClient.',
            },
            {
              name: '@relay/queue/consumer',
              message: 'apps/web produces jobs; only apps/worker consumes them.',
            },
          ],
          patterns: [
            {
              group: ['bullmq'],
              message: 'Use @relay/queue. Direct bullmq access belongs to packages/queue.',
            },
          ],
        },
      ],
    },
  },
);
